# **Indexación y selección** 

La indexación y la selección son técnicas utilizadas para **acceder y manipular** datos de manera eficiente. La indexación consiste en asignar identificadores únicos a las filas y columnas de estructuras de datos como _DataFrames_ y _Series_, facilitando su identificación y organización. Por otro lado, la selección se refiere al proceso de extraer subconjuntos de datos basados en estos identificadores (etiquetas o posiciones) y/o utilizando condiciones específicas dentro de estas estructuras

En este artículo, explicaremos cómo aplicar las técnicas de indexación y selección para gestionar datos geoespaciales de manera eficiente utilizando _GeoPandas_. Esta biblioteca hereda los métodos de _pandas_ e introduce la selección mediante bounding box (BBOX), permitiendo filtrar datos dentro de áreas geográficas específicas.

Comencemos importando las librerías necesarias:

In [1]:
import geopandas as gpd
import warnings
warnings.filterwarnings("ignore")

A continuación, cargaremos los datos.

In [2]:
comercios = gpd.read_file('data/comercios.gpkg')
print(f'Cantidad de registros {comercios.shape[0]}')

Cantidad de registros 184789


Veamos sus columnas:

In [3]:
comercios.columns.values

array(['COD_LOTE', 'COD_MZNA', 'COD_SECT', 'COD_PISO', 'COD_EDIFICACION',
       'COD_USO', 'DESC_USO', 'ID_DIST', 'ID_PLANO', 'ID_LOTE',
       'ANIO_CAT', 'geometry'], dtype=object)

## **1. Selección con corchetes `[]`**

El operador de corchetes `[]` se usa para **seleccionar columnas** de un DataFrame y **filtrar filas según condiciones** 

### **1.1. Selección de columnas**

#### **Selección de una única columna**

Se debe indicar una **etiqueta o nombre de columna** entre corchetes.

```{admonition} Seleccionar una única columna
:class: tip

#### **`df[col1]`**
```

Ejemplo: Seleccionar la columna `DESC_USO`:

In [4]:
comercios['DESC_USO']

0                   PELUQUERIA
1         CENTROS VACACIONALES
2                   PELUQUERIA
3                    SASTRERIA
4                       HOSTAL
                  ...         
184784     TIENDA DE ABARROTES
184785     TIENDA DE ABARROTES
184786     TIENDA DE ABARROTES
184787     TIENDA DE ABARROTES
184788     TIENDA DE ABARROTES
Name: DESC_USO, Length: 184789, dtype: object

#### **Selección de múltiples columnas**

Se debe específicar una **lista de etiquetas o nombres de columnas** entre corchetes.

```{admonition} Seleccionar múltiples columnas
:class: tip

#### **`df[[col1,col2,col3]]`**
```

Ejemplo: Seleccionar columnas `COD_USO` y `DESC_USO`

In [5]:
comercios[['COD_USO', 'DESC_USO']]

COD_USO              DESC_USO
0        41403            PELUQUERIA
1        41302  CENTROS VACACIONALES
2        41403            PELUQUERIA
3        41206             SASTRERIA
4        41303                HOSTAL
...        ...                   ...
184784   33107   TIENDA DE ABARROTES
184785   33107   TIENDA DE ABARROTES
184786   33107   TIENDA DE ABARROTES
184787   33107   TIENDA DE ABARROTES
184788   33107   TIENDA DE ABARROTES

[184789 rows x 2 columns]

### **1.2. Selección por máscara**

Esta técnica permite **filtrar filas** utilizando **expresiones booleanas**, aplicando operadores como **and** (`&`), **or** (`|`) y **not** (`~`). Se denomina "máscara" porque genera un conjunto de valores `True` o `False`, donde solo los elementos marcados como `True` son seleccionados.

```{admonition} Seleccionar por máscara
:class: tip

#### **`df[<expression>]`**
```

Ejemplo: Seleccionar los comercios que cumplan las siguientes condiciones:

* Se encuentran en el distrito de La Victoria, Lima (código de distrito: 150115).
* Corresponden a la categoría de Tienda de Abarrotes.

Para ello, combinaremos ambas condiciones en una expresión lógica de la siguiente manera:

In [6]:
# Almacenamos las condiciones en variables
conDis = comercios['ID_DIST'] == '150115'
conUso = comercios['DESC_USO'] == 'TIENDA DE ABARROTES'

# Seleccionamos por máscara
comercios_victoria = comercios[conDis & conUso]

# Cantidad de registros filtrados
comercios_victoria.shape[0]

388

## **2. Selección por Etiqueta: `loc`**

Es un método de acceso **`loc`** permite seleccionar datos de un _DataFrame_ o _Series_ utilizando **etiquetas de fila y columna** en lugar de índices numéricos.

### **2.1. Selección de filas**

#### **Selección de una única fila**

Se debe indicar una **etiqueta de fila**

```{admonition} Seleccionar una única fila
:class: tip

#### **`df.loc[row1]`**
```

Ejemplo: Seleccionar toda la fila con la etiqueta 5

In [7]:
comercios.loc[5]

COD_LOTE                                                         016
COD_MZNA                                                         008
COD_SECT                                                          99
COD_PISO                                                          01
COD_EDIFICACION                                                     
COD_USO                                                        11107
DESC_USO                       FABRICACION DE PRODUCTOS DE PANADERIA
ID_DIST                                                       190102
ID_PLANO                                             PLN-00000126043
ID_LOTE                                               19010299008016
ANIO_CAT                                                        2015
geometry           MULTIPOLYGON (((-75.95005042399998 -10.6356952...
Name: 5, dtype: object

#### **Selección de múltiples filas**

Especificar una **lista de etiquetas** de fila.

```{admonition} Seleccionar múltiples filas
:class: tip

#### **`df.loc[[row1, row2, row3]]`**
```

Ejemplo: Seleccionar las fila con la etiqueta 5 y 10

In [8]:
comercios.loc[[5, 10]]

COD_LOTE COD_MZNA COD_SECT COD_PISO COD_EDIFICACION COD_USO  \
5       016      008       99       01                   11107   
10      012      019       99       01                   44501   

                                 DESC_USO ID_DIST         ID_PLANO  \
5   FABRICACION DE PRODUCTOS DE PANADERIA  190102  PLN-00000126043   
10                         COMUNICACIONES  190102  PLN-00000126043   

           ID_LOTE ANIO_CAT                                           geometry  
5   19010299008016     2015  MULTIPOLYGON (((-75.95005 -10.6357, -75.95 -10...  
10  19010299019012     2015  MULTIPOLYGON (((-75.9495 -10.63637, -75.9495 -...

#### **Selección de múltiples filas con slicing**

Para realizar esta selección, se debe especificar un **rango de etiquetas** de fila. Este método incluye la etiqueta de inicio y de fin en el resultado

```{admonition} Seleccionar con slicing
:class: tip

#### **`df.loc[rowA:rowN]`**
```

Ejemplo: Seleccionar un rango de filas desde el 5 hasta 10

In [9]:
comercios.loc[5:10]

COD_LOTE COD_MZNA COD_SECT COD_PISO COD_EDIFICACION COD_USO  \
5       016      008       99       01                   11107   
6       001      026       99       01                   33107   
7       015      015       99       01                   41303   
8       007      017       99       01                   45101   
9       024      010       99       01                   34104   
10      012      019       99       01                   44501   

                                 DESC_USO ID_DIST         ID_PLANO  \
5   FABRICACION DE PRODUCTOS DE PANADERIA  190102  PLN-00000126043   
6                     TIENDA DE ABARROTES  190102  PLN-00000126043   
7                                  HOSTAL  190102  PLN-00000126043   
8                                   BANCO  190102  PLN-00000126043   
9                                   BAZAR  190102  PLN-00000126043   
10                         COMUNICACIONES  190102  PLN-00000126043   

           ID_LOTE ANIO_CAT                                           geometry  
5   19010299008016     2015  MULTIPOLYGON (((-75.95005 -10.6357, -75.95 -10...  
6   19010299026001     2015  MULTIPOLYGON (((-75.9504 -10.63657, -75.9504 -...  
7   19010299015015     2015  MULTIPOLYGON (((-75.95116 -10.63647, -75.95114...  
8   19010299017007     2015  MULTIPOLYGON (((-75.95062 -10.63616, -75.95058...  
9   19010299010024     2015  MULTIPOLYGON (((-75.94891 -10.63627, -75.94891...  
10  19010299019012     2015  MULTIPOLYGON (((-75.9495 -10.63637, -75.9495 -...

### **2.2. Selección de columnas**

#### **Selección de una única columna**

Se debe proporcionar una **etiqueta o nombre** de columna como segundo argumento. En el primero, se indica una fila específica; sin embargo, también es posible usar `:` para seleccionar todas las filas.

```{admonition} Seleccionar una única columna
:class: tip

#### **`df.loc[:, col1]`**
```

Ejemplo: Seleccionar la columna `DESC_USO` y todas sus filas

In [10]:
comercios.loc[:, 'DESC_USO']

0                   PELUQUERIA
1         CENTROS VACACIONALES
2                   PELUQUERIA
3                    SASTRERIA
4                       HOSTAL
                  ...         
184784     TIENDA DE ABARROTES
184785     TIENDA DE ABARROTES
184786     TIENDA DE ABARROTES
184787     TIENDA DE ABARROTES
184788     TIENDA DE ABARROTES
Name: DESC_USO, Length: 184789, dtype: object

#### **Selección de múltiples columnas**

Se debe especificar una **lista de etiquetas o nombres** de columna como segundo argumento. En el primero, se indica una fila específica; sin embargo, también es posible usar `:` para seleccionar todas las filas.

```{admonition} Seleccionar múltiples columnas
:class: tip

#### **`df.loc[:, [col1, col2, col3]]`**
```

Ejemplo: Seleccionar las columnas `COD_USO`, `DESC_USO` e `ID_DIST`:

In [11]:
comercios.loc[:,['COD_USO','DESC_USO','ID_DIST']]

COD_USO              DESC_USO ID_DIST
0        41403            PELUQUERIA  190102
1        41302  CENTROS VACACIONALES  190102
2        41403            PELUQUERIA  190102
3        41206             SASTRERIA  190102
4        41303                HOSTAL  190102
...        ...                   ...     ...
184784   33107   TIENDA DE ABARROTES  040102
184785   33107   TIENDA DE ABARROTES  150118
184786   33107   TIENDA DE ABARROTES  150103
184787   33107   TIENDA DE ABARROTES  140105
184788   33107   TIENDA DE ABARROTES  150103

[184789 rows x 3 columns]

#### **Selección de múltiples columnas con slicing**

Para realizar esta selección, es necesario indicar un **rango de etiquetas** de columna. El primer argumento corresponde a una fila específica, aunque también se puede utilizar `:` para seleccionar todas las filas. Este método incluye tanto la etiqueta de inicio como la de fin en el resultado.

```{admonition} Seleccionar con slicing
:class: tip

#### **`df.loc[:, colA:colN]`**
```

Ejemplo: Seleccionar las columnas, desde `COD_USO` hasta `ID_DIST`:

In [12]:
comercios.loc[:, 'COD_USO':'ID_DIST']

COD_USO              DESC_USO ID_DIST
0        41403            PELUQUERIA  190102
1        41302  CENTROS VACACIONALES  190102
2        41403            PELUQUERIA  190102
3        41206             SASTRERIA  190102
4        41303                HOSTAL  190102
...        ...                   ...     ...
184784   33107   TIENDA DE ABARROTES  040102
184785   33107   TIENDA DE ABARROTES  150118
184786   33107   TIENDA DE ABARROTES  150103
184787   33107   TIENDA DE ABARROTES  140105
184788   33107   TIENDA DE ABARROTES  150103

[184789 rows x 3 columns]

### **2.3. Selección de filas y columnas**

#### **Selección de una fila y una columa**

Se debe especificar **una etiqueta** de fila y de columna.

```{admonition} Seleccionar una fila y una columna
:class: tip

#### **`df.loc[row1, col1]`**
```

Ejemplo: Seleccionar el valor de la fila 5 y columna `DESC_USO`:

In [13]:
comercios.loc[5, 'DESC_USO']

'FABRICACION DE PRODUCTOS DE PANADERIA'

#### **Selección de múltiples filas y columnas**

Se debe especificar una **lista de etiquetas** de filas y columnas.

```{admonition} Seleccionar múltiples filas y columnas
:class: tip

#### **`df.loc[[row1, row2, row3], [col1, col2, col3]]`**
```

Ejemplo: Seleccionar las filas 0, 5 y 10 y las columnas `COD_USO` y `DESC_USO`:

In [14]:
comercios.loc[[0, 5, 10], ['COD_USO', 'DESC_USO']]

COD_USO                               DESC_USO
0    41403                             PELUQUERIA
5    11107  FABRICACION DE PRODUCTOS DE PANADERIA
10   44501                         COMUNICACIONES

#### **Selección de múltiples filas y columnas con slicing**

Se debe especificar una **rango de etiquetas** de filas y de columnas. Este método incluye las etiquetas de inicio y de fin en el resultado.

```{admonition} Seleccionar con Slicing
:class: tip

#### **`df.loc[rowA:rowN, colA:colN]`**
```

Ejemplo: Seleccionar desde la fila 1 a las 4 y desde la columna `COD_PISO` a `DESC_USO`:

In [15]:
comercios.loc[1:4, 'COD_PISO':'DESC_USO']

COD_PISO COD_EDIFICACION COD_USO              DESC_USO
1       01                   41302  CENTROS VACACIONALES
2       01                   41403            PELUQUERIA
3       01                   41206             SASTRERIA
4       02                   41303                HOSTAL

### **2.4. Selección por máscara**

Como se mencionó anteriormente, la selección por máscara es una técnica que permite **filtrar filas** mediante **expresiones booleanas**, utilizando operadores como **and** (`&`), **or** (`|`) y **not** (`~`). Se denomina "máscara" porque genera un conjunto de valores `True` o `False`, **seleccionando** únicamente aquellos donde la condición es `True`.

```{admonition} Seleccionar por máscara
:class: tip

#### **`df.loc[<expression>]`**
```

Ejemplo: Seleccionar los comercios que cumplan las siguientes condiciones:

* Se encuentran en el distrito de Ate, Lima (código de distrito: 150103).
* Corresponden a la categoría de Hostal.

Para ello, combinaremos ambas condiciones en una expresión de la siguiente manera:

In [16]:
# Almacenamos las condiciones en variables
conDis2 = comercios['ID_DIST'] == '150103'
conUso2 = comercios['DESC_USO'] == 'HOSTAL'

# Seleccionamos por máscara
comercios_ate = comercios[conDis2 & conUso2]

# Cantidad de registros filtrados
comercios_ate.shape[0]

475

### **2.5. Actualización de valores**

#### **Actualización de un valor**

Para modificar un valor, accedemos a él mediante su **etiqueta de fila y de columna** y lo actualizamos directamente.

```{admonition} Actualización de un valor
:class: tip

#### **`df.loc[rowA1, col1] = <nuevo_valor>`**
```

Ejemplo: Actualizar el valor de la fila 5 y la columna `DESC_USO` por "ELABORACION DE PRODUCTOS ALIMENTICIOS"

Comencemos consultando el valor:

In [17]:
comercios.loc[5,'DESC_USO']

'FABRICACION DE PRODUCTOS DE PANADERIA'

Ahora, modifiquemos el valor:

In [18]:
comercios.loc[5,'DESC_USO'] = 'ELABORACION DE PRODUCTOS ALIMENTICIOS'

Volvamos a consultar:

In [19]:
comercios.loc[5,'DESC_USO']

'ELABORACION DE PRODUCTOS ALIMENTICIOS'

#### **Actualización con máscara**

Permite **actualizar valores** en función de **condiciones lógicas**, modificando solo aquellos elementos que **cumplan la condición**.

```{admonition} Actualización con máscara
:class: tip

#### **`df.loc[<expression>, <col1>] = <nuevo_valor>`**
```

Ejemplo: Actualizar el valor de `DESC_USO` a "ELABORACIÓN DE PRODUCTOS ALIMENTICIOS" en todas las filas donde `COD_USO` sea igual a 11107.

Comenzamos haciendo una selección por máscara de `COD_USO == 11107`:

In [20]:
comercios.loc[comercios.COD_USO=='11107',['COD_USO','DESC_USO']]

COD_USO                               DESC_USO
5        11107  ELABORACION DE PRODUCTOS ALIMENTICIOS
1035     11107  FABRICACION DE PRODUCTOS DE PANADERIA
1259     11107  FABRICACION DE PRODUCTOS DE PANADERIA
1372     11107  FABRICACION DE PRODUCTOS DE PANADERIA
1913     11107  FABRICACION DE PRODUCTOS DE PANADERIA
...        ...                                    ...
183742   11107  FABRICACION DE PRODUCTOS DE PANADERIA
183775   11107  FABRICACION DE PRODUCTOS DE PANADERIA
184365   11107  FABRICACION DE PRODUCTOS DE PANADERIA
184559   11107  FABRICACION DE PRODUCTOS DE PANADERIA
184647   11107  FABRICACION DE PRODUCTOS DE PANADERIA

[320 rows x 2 columns]

Modifiquemos el valor según la condición:

In [21]:
comercios.loc[comercios.COD_USO=='11107', 'DESC_USO'] = 'ELABORACIÓN DE PRODUCTOS ALIMENTICIOS'

Volvamos a consultar:

In [22]:
comercios.loc[comercios.COD_USO=='11107',['COD_USO','DESC_USO']]

COD_USO                               DESC_USO
5        11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1035     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1259     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1372     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1913     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
...        ...                                    ...
183742   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
183775   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
184365   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
184559   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
184647   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS

[320 rows x 2 columns]

## **3. Selección por Posición: `iloc`**

El método `.iloc` permite seleccionar datos por **posición** en lugar de por etiquetas. Se basa en **índices numéricos** para acceder a filas y columnas de un `GeoDataFrame`.

### **3.1. Selección de filas**

#### **Selección de una única fila**

Especificar la **posición** de la fila:

```{admonition} Seleccionar una única fila
:class: tip

#### **`df.iloc[i]`**
```

Ejemplo: Seleccionar la fila en la posición 2

In [23]:
comercios.iloc[2]

COD_LOTE                                                         004
COD_MZNA                                                         017
COD_SECT                                                          99
COD_PISO                                                          01
COD_EDIFICACION                                                     
COD_USO                                                        41403
DESC_USO                                                  PELUQUERIA
ID_DIST                                                       190102
ID_PLANO                                             PLN-00000126043
ID_LOTE                                               19010299017004
ANIO_CAT                                                        2015
geometry           MULTIPOLYGON (((-75.950586741 -10.636322932999...
Name: 2, dtype: object

#### **Selección de múltiples filas**

Especificar una **lista de posiciones** de fila.

```{admonition} Seleccionar múltiples filas
:class: tip

#### **`df.iloc[[i, j, k]]`**
```

Ejemplo: Seleccionar las filas en la posicion 3, 7, 11

In [24]:
comercios.iloc[[3, 7, 9]]

COD_LOTE COD_MZNA COD_SECT COD_PISO COD_EDIFICACION COD_USO   DESC_USO  \
3      015      015       99       01                   41206  SASTRERIA   
7      015      015       99       01                   41303     HOSTAL   
9      024      010       99       01                   34104      BAZAR   

  ID_DIST         ID_PLANO         ID_LOTE ANIO_CAT  \
3  190102  PLN-00000126043  19010299015015     2015   
7  190102  PLN-00000126043  19010299015015     2015   
9  190102  PLN-00000126043  19010299010024     2015   

                                            geometry  
3  MULTIPOLYGON (((-75.95124 -10.6365, -75.95122 ...  
7  MULTIPOLYGON (((-75.95116 -10.63647, -75.95114...  
9  MULTIPOLYGON (((-75.94891 -10.63627, -75.94891...

#### **Selección de múltiples filas con slicing**

Especificar un **rango de posiciones** de fila. Este método incluye el índice de inicio, pero excluye el índice de fin en el resultado.

```{admonition} Seleccionar con slicing
:class: tip

#### **`df.iloc[i:k]`**
```

Ejemplo: Seleccionar las filas desde el 3 hasta el 8

In [25]:
comercios.iloc[3:9]

COD_LOTE COD_MZNA COD_SECT COD_PISO COD_EDIFICACION COD_USO  \
3      015      015       99       01                   41206   
4      008      029       99       02                   41303   
5      016      008       99       01                   11107   
6      001      026       99       01                   33107   
7      015      015       99       01                   41303   
8      007      017       99       01                   45101   

                                DESC_USO ID_DIST         ID_PLANO  \
3                              SASTRERIA  190102  PLN-00000126043   
4                                 HOSTAL  190102  PLN-00000126043   
5  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS  190102  PLN-00000126043   
6                    TIENDA DE ABARROTES  190102  PLN-00000126043   
7                                 HOSTAL  190102  PLN-00000126043   
8                                  BANCO  190102  PLN-00000126043   

          ID_LOTE ANIO_CAT                                           geometry  
3  19010299015015     2015  MULTIPOLYGON (((-75.95124 -10.6365, -75.95122 ...  
4  19010299029008     2015  MULTIPOLYGON (((-75.94989 -10.63661, -75.94988...  
5  19010299008016     2015  MULTIPOLYGON (((-75.95005 -10.6357, -75.95 -10...  
6  19010299026001     2015  MULTIPOLYGON (((-75.9504 -10.63657, -75.9504 -...  
7  19010299015015     2015  MULTIPOLYGON (((-75.95116 -10.63647, -75.95114...  
8  19010299017007     2015  MULTIPOLYGON (((-75.95062 -10.63616, -75.95058...

### **3.2. Selección de columnas**

#### **Selección de una única columna**

Se debe especificar la **posición** de la columna como segundo argumento. En el primero, se indica una fila específica; sin embargo, también es posible usar `:` para seleccionar todas las filas.

```{admonition} Seleccionar una única columna
:class: tip

#### **`df.iloc[:, m]`**
```

Ejemplo: Seleccionemos la columna en la posición 6 (es la columna `COD_USO`)

In [26]:
comercios.iloc[:, 6]

0                   PELUQUERIA
1         CENTROS VACACIONALES
2                   PELUQUERIA
3                    SASTRERIA
4                       HOSTAL
                  ...         
184784     TIENDA DE ABARROTES
184785     TIENDA DE ABARROTES
184786     TIENDA DE ABARROTES
184787     TIENDA DE ABARROTES
184788     TIENDA DE ABARROTES
Name: DESC_USO, Length: 184789, dtype: object

#### **Selección de múltiples columnas**

Se debe especificar una **lista de posiciones** de columna como segundo argumento. En el primero, se indica una fila específica; sin embargo, también es posible usar `:` para seleccionar todas las filas.

```{admonition} Seleccionar múltiples columnas
:class: tip

#### **`df.iloc[:, [m, n, p]]`**
```

Ejemplo: Seleccionar los índices de columnas 5, 6 y 7

In [27]:
comercios.iloc[:, [5,6,7]]

COD_USO              DESC_USO ID_DIST
0        41403            PELUQUERIA  190102
1        41302  CENTROS VACACIONALES  190102
2        41403            PELUQUERIA  190102
3        41206             SASTRERIA  190102
4        41303                HOSTAL  190102
...        ...                   ...     ...
184784   33107   TIENDA DE ABARROTES  040102
184785   33107   TIENDA DE ABARROTES  150118
184786   33107   TIENDA DE ABARROTES  150103
184787   33107   TIENDA DE ABARROTES  140105
184788   33107   TIENDA DE ABARROTES  150103

[184789 rows x 3 columns]

#### **Selección de múltiples columnas con slicing**

Para realizar esta selección, es necesario indicar un **rango de posiciones** de columna. El primer argumento corresponde a una posición de fila, aunque también se puede utilizar `:` para seleccionar todas las filas. Este método incluye el índice de inicio, pero excluye el índice de fin en el resultado.

```{admonition} Seleccionar con slicing
:class: tip

#### **`df.iloc[:, m:p]`**
```

Ejemplo: Seleccionar las columnas desde la posición 5 hasta la 7, inclusive.

In [28]:
comercios.iloc[:, 5:8]

COD_USO              DESC_USO ID_DIST
0        41403            PELUQUERIA  190102
1        41302  CENTROS VACACIONALES  190102
2        41403            PELUQUERIA  190102
3        41206             SASTRERIA  190102
4        41303                HOSTAL  190102
...        ...                   ...     ...
184784   33107   TIENDA DE ABARROTES  040102
184785   33107   TIENDA DE ABARROTES  150118
184786   33107   TIENDA DE ABARROTES  150103
184787   33107   TIENDA DE ABARROTES  140105
184788   33107   TIENDA DE ABARROTES  150103

[184789 rows x 3 columns]

### **3.3. Selección de filas y columnas**

#### **Selección de una fila y una columa**

Se debe especificar una **posición** de fila y de columna.

```{admonition} Seleccionar una fila y una columna
:class: tip

#### **`df.iloc[i, m]`**
```

Ejemplo: Seleccionar el valor ubicado en la fila de posición 5 y la columna de posición 6.

In [29]:
comercios.iloc[5,6]

'ELABORACIÓN DE PRODUCTOS ALIMENTICIOS'

#### **Selección de mútiples filas y columnas**

Se debe especificar una **lista de posiciones** de filas y columnas.

```{admonition} Seleccionar múltiples filas y columnas
:class: tip

#### **`df.iloc[[i, j, k], [m, n, p]]`**
```

Ejemplo: Seleccionar las filas 0, 5 y 10 y las columnas 5 y 6:

In [30]:
comercios.iloc[[0,5,10],[5,6]]

COD_USO                               DESC_USO
0    41403                             PELUQUERIA
5    11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
10   44501                         COMUNICACIONES

#### **Selección de múltiples filas y columnas con slicing**

Se debe especificar una **rango de posiciones** de filas y columnas. Este método incluye el índice de inicio, pero excluye el índice de fin en el resultado.

```{admonition} Seleccionar múltiples filas y columnas con Slicing
:class: tip

#### **`df.iloc[i:k, m:p]`**
```

Ejemplo: Seleccionar desde la fila 1 a las 4 y desde la columna 4 a 6, inclusive:

In [31]:
comercios.iloc[1:5, 4:7]

COD_EDIFICACION COD_USO              DESC_USO
1                   41302  CENTROS VACACIONALES
2                   41403            PELUQUERIA
3                   41206             SASTRERIA
4                   41303                HOSTAL

### **3.5. Actualización de valores**

La actualización de valores con **`.iloc`** se realiza mediante posiciones numéricas de filas y columnas. No admite el uso directo de condiciones booleanas para filtrar datos antes de modificarlos.

#### **Actualización de un valor**

Para modificar un valor específico, indicamos la **posición** de la fila y la columna:

```{admonition} Actualización de un valor
:class: tip

#### **`df.iloc[i, m] = <nuevo_valor>`**
```

Ejemplo: Modificaremos el valor en la fila ubicada en la posición 5 y la columna en la posición 6, asignándole "FABRICACIÓN DE PRODUCTOS DE PANADERÍA".

Comencemos consultado el valor actual en esa posición:

In [32]:
comercios.iloc[5,6]

'ELABORACIÓN DE PRODUCTOS ALIMENTICIOS'

Modifiquemos:

In [33]:
comercios.iloc[5,6] = 'FABRICACIÓN DE PRODUCTOS DE PANADERÍA'

Verifiquemos:

In [34]:
comercios.iloc[5,6]

'FABRICACIÓN DE PRODUCTOS DE PANADERÍA'

#### **Actualizar múltiples valores**

Podemos actualizar múltiples valores usando un **rango o una lista de posiciones de fila** junto con las **posiciones de las columnas** correspondientes.

```{admonition} Actualización de múltiples valores
:class: tip

#### `df.iloc[i:k, m] = <nuevo_valor>`

#### `df.iloc[list_index, m] = <nuevo_valor>`
```

Ejemplo: Modificar el valor de `DESC_USO` (indice 6) a "FABRICACIÓN DE PRODUCTOS DE PANADERÍA" en todas las filas donde `COD_USO == '11107'`.

Comenzemos consultando las filas cuyo `COD_USO=='11107'`

In [35]:
comercios.loc[comercios.COD_USO=='11107', ['COD_USO','DESC_USO']]

COD_USO                               DESC_USO
5        11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
1035     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1259     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1372     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
1913     11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
...        ...                                    ...
183742   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
183775   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
184365   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
184559   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS
184647   11107  ELABORACIÓN DE PRODUCTOS ALIMENTICIOS

[320 rows x 2 columns]

Obtener los índices:

In [36]:
index_upd = comercios.loc[comercios.COD_USO=='11107'].index
index_upd

Int64Index([     5,   1035,   1259,   1372,   1913,   2088,   2625,   2706,
              3379,   3410,
            ...
            182066, 182101, 182333, 182840, 183292, 183742, 183775, 184365,
            184559, 184647],
           dtype='int64', length=320)

Actualizar múltiples valores:

In [37]:
comercios.iloc[index_upd, 6] = 'FABRICACIÓN DE PRODUCTOS DE PANADERÍA'

Verifiquemos

In [38]:
comercios.loc[comercios.COD_USO=='11107', ['COD_USO','DESC_USO']]

COD_USO                               DESC_USO
5        11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
1035     11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
1259     11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
1372     11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
1913     11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
...        ...                                    ...
183742   11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
183775   11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
184365   11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
184559   11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA
184647   11107  FABRICACIÓN DE PRODUCTOS DE PANADERÍA

[320 rows x 2 columns]

## **4. Selección por cuadro delimitador: `cx`**

_GeoPandas_ permite realizar selecciones espaciales mediante un cuadro delimitador (bounding box) utilizando la propiedad **[cx](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.cx.html#geopandas.GeoDataFrame.cx)**. Esta funcionalidad facilita la selección de datos dentro de un área geográfica definida por coordenadas mínimas y máximas.

Esta técnica es útil para extraer subconjuntos de datos espaciales dentro de un área de interés específica sin necesidad de realizar consultas geométricas complejas.

```{admonition} Actualización de un valor
:class: tip

#### **`gdf.cx[xmin:xmax, ymin:ymax]`**
```

Ejemplo: Seleccionar el subconjunto de datos que se ubique dentro del BBOX: (xmin: -77.052133, xmax:-77.048287, ymin: -12.07537, ymax:-12.072682)

In [39]:
comercios_filtro = comercios.cx[-77.052133:-77.048287, -12.07537:-12.072682]

In [42]:
# Crear Poligono de BBOX
from shapely.geometry import box
bbox = (-77.052133, -12.07537, -77.048287, -12.072682)
polygon = box(*bbox)
gdfBox = gpd.GeoDataFrame({"geometry": [polygon]}, crs="EPSG:4326")

# Visualizar
m = comercios_filtro.explore(zoom_start=17)
gdfBox.explore(m=m, color='red', fill=False)

## **Conclusiones**

Al explorar los métodos de selección en GeoPandas (`[]`, `.loc`, `.iloc` y `.cx`), podemos destacar lo siguiente:

* **`Acceso básico ([])`**: Permite **acceder a columnas directamente** mediante su nombre, pero tiene limitaciones en la selección de filas.
* **`Selección con .loc`**: Se basa en **etiquetas** (nombres de filas y columnas) y permite **selecciones avanzadas** como máscaras booleanas y actualización de valores.
* **`Selección con .iloc`**: Utiliza índices posicionales, lo que resulta **útil cuando no conocemos las etiquetas** o necesitamos acceder a datos de manera ordenada.
* **`Selección con .cx`**: Exclusivo de GeoPandas, facilita la **selección de datos espaciales** dentro de un **cuadro delimitador** (bounding box).

Cada método tiene su propósito y es importante elegir el más adecuado según el contexto, ya sea para acceder, filtrar o actualizar datos de manera eficiente.